language: go

go:
  - tip

before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.4.0.deb && sudo dpkg -i --force-confnew elasticsearch-6.4.0.deb && sudo service elasticsearch restart

install:
  - export GOPATH=$GOPATH:$TRAVIS_BUILD_DIR/vendor/
  - go get github.com/onsi/ginkgo
  - go get github.com/onsi/gomega
  - go get github.com/stretchr/testify/mock
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls

script:
  - $HOME/gopath/bin/goveralls -package=./lib -service=travis-ci
  - (cd app && yarn && yarn tsc)

before_script:
  - sleep 5

services:
  - elasticsearch