language: go

go:
  - tip

install:
  - go get
  - go get github.com/onsi/ginkgo
  - go get github.com/onsi/gomega
  - go get github.com/stretchr/testify/mock
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls

script: $HOME/gopath/bin/goveralls -package=./lib -service=travis-ci

before_script:
  - sleep 10

services:
  - elasticsearch