language: go

go:
  - tip

install:
  - export GOPATH=$GOPATH:$TRAVIS_BUILD_DIR/Godeps/_workspace
  - go get github.com/onsi/ginkgo
  - go get github.com/onsi/gomega
  - go get github.com/stretchr/testify/mock
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls

script: $HOME/gopath/bin/goveralls -package=./lib -service=travis-ci

before_script:
  - sleep 5

services:
  - elasticsearch