language: go

go:
  - tip

install:
  - go get
  - go get github.com/onsi/ginkgo
  - go get github.com/onsi/gomega
  - go get github.com/stretchr/testify/mock

script: go test ./ ./lib

before_script:
  - sleep 10

services:
  - elasticsearch