System.config({
  baseURL: "./",
  defaultJSExtensions: true,
  transpiler: false,
  paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },
  bundles: {
    "build.js": [
      "npm:react-dom@15.0.1.js",
      "npm:react-dom@15.0.1/index.js",
      "npm:react@15.0.1/lib/ReactDOM.js",
      "github:jspm/nodelibs-process@0.1.2.js",
      "github:jspm/nodelibs-process@0.1.2/index.js",
      "npm:process@0.11.2.js",
      "npm:process@0.11.2/browser.js",
      "npm:fbjs@0.8.0/lib/ExecutionEnvironment.js",
      "npm:fbjs@0.8.0/lib/warning.js",
      "npm:fbjs@0.8.0/lib/emptyFunction.js",
      "npm:react@15.0.1/lib/renderSubtreeIntoContainer.js",
      "npm:react@15.0.1/lib/ReactMount.js",
      "npm:react@15.0.1/lib/shouldUpdateReactComponent.js",
      "npm:react@15.0.1/lib/setInnerHTML.js",
      "npm:react@15.0.1/lib/createMicrosoftUnsafeLocalFunction.js",
      "npm:fbjs@0.8.0/lib/invariant.js",
      "npm:react@15.0.1/lib/instantiateReactComponent.js",
      "npm:react@15.0.1/lib/ReactNativeComponent.js",
      "npm:object-assign@4.0.1.js",
      "npm:object-assign@4.0.1/index.js",
      "npm:react@15.0.1/lib/ReactEmptyComponent.js",
      "npm:react@15.0.1/lib/ReactCompositeComponent.js",
      "npm:fbjs@0.8.0/lib/emptyObject.js",
      "npm:react@15.0.1/lib/ReactUpdateQueue.js",
      "npm:react@15.0.1/lib/ReactUpdates.js",
      "npm:react@15.0.1/lib/Transaction.js",
      "npm:react@15.0.1/lib/ReactReconciler.js",
      "npm:react@15.0.1/lib/ReactInstrumentation.js",
      "npm:react@15.0.1/lib/ReactDebugTool.js",
      "npm:react@15.0.1/lib/ReactInvalidSetStateWarningDevTool.js",
      "npm:react@15.0.1/lib/ReactRef.js",
      "npm:react@15.0.1/lib/ReactOwner.js",
      "npm:react@15.0.1/lib/ReactPerf.js",
      "npm:react@15.0.1/lib/ReactFeatureFlags.js",
      "npm:react@15.0.1/lib/PooledClass.js",
      "npm:react@15.0.1/lib/CallbackQueue.js",
      "npm:react@15.0.1/lib/ReactInstanceMap.js",
      "npm:react@15.0.1/lib/ReactCurrentOwner.js",
      "npm:react@15.0.1/lib/ReactPropTypeLocationNames.js",
      "npm:react@15.0.1/lib/ReactPropTypeLocations.js",
      "npm:fbjs@0.8.0/lib/keyMirror.js",
      "npm:react@15.0.1/lib/ReactNodeTypes.js",
      "npm:react@15.0.1/lib/ReactElement.js",
      "npm:react@15.0.1/lib/canDefineProperty.js",
      "npm:react@15.0.1/lib/ReactErrorUtils.js",
      "npm:react@15.0.1/lib/ReactComponentEnvironment.js",
      "npm:react@15.0.1/lib/ReactMarkupChecksum.js",
      "npm:react@15.0.1/lib/adler32.js",
      "npm:react@15.0.1/lib/ReactDOMFeatureFlags.js",
      "npm:react@15.0.1/lib/ReactDOMContainerInfo.js",
      "npm:react@15.0.1/lib/validateDOMNesting.js",
      "npm:react@15.0.1/lib/ReactDOMComponentTree.js",
      "npm:react@15.0.1/lib/ReactDOMComponentFlags.js",
      "npm:react@15.0.1/lib/DOMProperty.js",
      "npm:react@15.0.1/lib/ReactBrowserEventEmitter.js",
      "npm:react@15.0.1/lib/isEventSupported.js",
      "npm:react@15.0.1/lib/getVendorPrefixedEventName.js",
      "npm:react@15.0.1/lib/ViewportMetrics.js",
      "npm:react@15.0.1/lib/ReactEventEmitterMixin.js",
      "npm:react@15.0.1/lib/EventPluginHub.js",
      "npm:react@15.0.1/lib/forEachAccumulated.js",
      "npm:react@15.0.1/lib/accumulateInto.js",
      "npm:react@15.0.1/lib/EventPluginUtils.js",
      "npm:react@15.0.1/lib/EventConstants.js",
      "npm:react@15.0.1/lib/EventPluginRegistry.js",
      "npm:react@15.0.1/lib/DOMLazyTree.js",
      "npm:react@15.0.1/lib/setTextContent.js",
      "npm:react@15.0.1/lib/escapeTextContentForBrowser.js",
      "npm:react@15.0.1/lib/getNativeComponentFromComposite.js",
      "npm:react@15.0.1/lib/findDOMNode.js",
      "npm:react@15.0.1/lib/ReactVersion.js",
      "npm:react@15.0.1/lib/ReactDefaultInjection.js",
      "npm:react@15.0.1/lib/ReactDefaultPerf.js",
      "npm:fbjs@0.8.0/lib/performanceNow.js",
      "npm:fbjs@0.8.0/lib/performance.js",
      "npm:react@15.0.1/lib/ReactDefaultPerfAnalysis.js",
      "npm:react@15.0.1/lib/SimpleEventPlugin.js",
      "npm:fbjs@0.8.0/lib/keyOf.js",
      "npm:react@15.0.1/lib/getEventCharCode.js",
      "npm:react@15.0.1/lib/SyntheticWheelEvent.js",
      "npm:react@15.0.1/lib/SyntheticMouseEvent.js",
      "npm:react@15.0.1/lib/getEventModifierState.js",
      "npm:react@15.0.1/lib/SyntheticUIEvent.js",
      "npm:react@15.0.1/lib/getEventTarget.js",
      "npm:react@15.0.1/lib/SyntheticEvent.js",
      "npm:react@15.0.1/lib/SyntheticTransitionEvent.js",
      "npm:react@15.0.1/lib/SyntheticTouchEvent.js",
      "npm:react@15.0.1/lib/SyntheticDragEvent.js",
      "npm:react@15.0.1/lib/SyntheticKeyboardEvent.js",
      "npm:react@15.0.1/lib/getEventKey.js",
      "npm:react@15.0.1/lib/SyntheticFocusEvent.js",
      "npm:react@15.0.1/lib/SyntheticClipboardEvent.js",
      "npm:react@15.0.1/lib/SyntheticAnimationEvent.js",
      "npm:react@15.0.1/lib/EventPropagators.js",
      "npm:fbjs@0.8.0/lib/EventListener.js",
      "npm:react@15.0.1/lib/SelectEventPlugin.js",
      "npm:fbjs@0.8.0/lib/shallowEqual.js",
      "npm:react@15.0.1/lib/isTextInputElement.js",
      "npm:fbjs@0.8.0/lib/getActiveElement.js",
      "npm:react@15.0.1/lib/ReactInputSelection.js",
      "npm:fbjs@0.8.0/lib/focusNode.js",
      "npm:fbjs@0.8.0/lib/containsNode.js",
      "npm:fbjs@0.8.0/lib/isTextNode.js",
      "npm:fbjs@0.8.0/lib/isNode.js",
      "npm:react@15.0.1/lib/ReactDOMSelection.js",
      "npm:react@15.0.1/lib/getTextContentAccessor.js",
      "npm:react@15.0.1/lib/getNodeForCharacterOffset.js",
      "npm:react@15.0.1/lib/SVGDOMPropertyConfig.js",
      "npm:react@15.0.1/lib/ReactReconcileTransaction.js",
      "npm:react@15.0.1/lib/ReactInjection.js",
      "npm:react@15.0.1/lib/ReactClass.js",
      "npm:react@15.0.1/lib/ReactNoopUpdateQueue.js",
      "npm:react@15.0.1/lib/ReactComponent.js",
      "npm:react@15.0.1/lib/ReactEventListener.js",
      "npm:fbjs@0.8.0/lib/getUnboundedScrollPosition.js",
      "npm:react@15.0.1/lib/ReactDefaultBatchingStrategy.js",
      "npm:react@15.0.1/lib/ReactDOMTextComponent.js",
      "npm:react@15.0.1/lib/DOMChildrenOperations.js",
      "npm:react@15.0.1/lib/ReactMultiChildUpdateTypes.js",
      "npm:react@15.0.1/lib/Danger.js",
      "npm:fbjs@0.8.0/lib/getMarkupWrap.js",
      "npm:fbjs@0.8.0/lib/createNodesFromMarkup.js",
      "npm:fbjs@0.8.0/lib/createArrayFromMixed.js",
      "npm:react@15.0.1/lib/ReactDOMTreeTraversal.js",
      "npm:react@15.0.1/lib/ReactDOMEmptyComponent.js",
      "npm:react@15.0.1/lib/ReactDOMComponent.js",
      "npm:react@15.0.1/lib/ReactMultiChild.js",
      "npm:react@15.0.1/lib/flattenChildren.js",
      "npm:react@15.0.1/lib/traverseAllChildren.js",
      "npm:react@15.0.1/lib/getIteratorFn.js",
      "npm:react@15.0.1/lib/ReactChildReconciler.js",
      "npm:react@15.0.1/lib/ReactDOMTextarea.js",
      "npm:react@15.0.1/lib/LinkedValueUtils.js",
      "npm:react@15.0.1/lib/ReactPropTypes.js",
      "npm:react@15.0.1/lib/DOMPropertyOperations.js",
      "npm:react@15.0.1/lib/quoteAttributeValueForBrowser.js",
      "npm:react@15.0.1/lib/ReactDOMInstrumentation.js",
      "npm:react@15.0.1/lib/ReactDOMDebugTool.js",
      "npm:react@15.0.1/lib/ReactDOMUnknownPropertyDevtool.js",
      "npm:react@15.0.1/lib/ReactDOMSelect.js",
      "npm:react@15.0.1/lib/ReactDOMOption.js",
      "npm:react@15.0.1/lib/ReactChildren.js",
      "npm:react@15.0.1/lib/ReactDOMInput.js",
      "npm:react@15.0.1/lib/ReactDOMButton.js",
      "npm:react@15.0.1/lib/ReactComponentBrowserEnvironment.js",
      "npm:react@15.0.1/lib/ReactDOMIDOperations.js",
      "npm:react@15.0.1/lib/DOMNamespaces.js",
      "npm:react@15.0.1/lib/CSSPropertyOperations.js",
      "npm:fbjs@0.8.0/lib/memoizeStringOnly.js",
      "npm:fbjs@0.8.0/lib/hyphenateStyleName.js",
      "npm:fbjs@0.8.0/lib/hyphenate.js",
      "npm:react@15.0.1/lib/dangerousStyleValue.js",
      "npm:react@15.0.1/lib/CSSProperty.js",
      "npm:fbjs@0.8.0/lib/camelizeStyleName.js",
      "npm:fbjs@0.8.0/lib/camelize.js",
      "npm:react@15.0.1/lib/AutoFocusUtils.js",
      "npm:react@15.0.1/lib/HTMLDOMPropertyConfig.js",
      "npm:react@15.0.1/lib/EnterLeaveEventPlugin.js",
      "npm:react@15.0.1/lib/DefaultEventPluginOrder.js",
      "npm:react@15.0.1/lib/ChangeEventPlugin.js",
      "npm:react@15.0.1/lib/BeforeInputEventPlugin.js",
      "npm:react@15.0.1/lib/SyntheticInputEvent.js",
      "npm:react@15.0.1/lib/SyntheticCompositionEvent.js",
      "npm:react@15.0.1/lib/FallbackCompositionState.js",
      "npm:react-date-picker@4.0.10.js",
      "npm:react-date-picker@4.0.10/lib/index.js",
      "npm:react-date-picker@4.0.10/lib/onEnter.js",
      "npm:react-date-picker@4.0.10/lib/toMoment.js",
      "npm:react-date-picker@4.0.10/lib/config.js",
      "npm:react-date-picker@4.0.10/lib/utils/getWeekDayNames.js",
      "npm:moment@2.12.0.js",
      "npm:moment@2.12.0/moment.js",
      "npm:react-date-picker@4.0.10/lib/Header.js",
      "npm:react@15.0.1.js",
      "npm:react@15.0.1/react.js",
      "npm:react@15.0.1/lib/React.js",
      "npm:react@15.0.1/lib/onlyChild.js",
      "npm:react@15.0.1/lib/ReactElementValidator.js",
      "npm:react@15.0.1/lib/ReactDOMFactories.js",
      "npm:fbjs@0.8.0/lib/mapObject.js",
      "npm:react-date-picker@4.0.10/lib/DecadeView.js",
      "npm:react-date-picker@4.0.10/lib/utils/isInRange.js",
      "npm:react-date-picker@4.0.10/lib/utils/asConfig.js",
      "npm:react-date-picker@4.0.10/lib/utils/format.js",
      "npm:react-date-picker@4.0.10/lib/YearView.js",
      "npm:react-date-picker@4.0.10/lib/MonthView.js",
      "npm:page@1.7.1.js",
      "npm:page@1.7.1/index.js",
      "npm:path-to-regexp@1.2.1.js",
      "npm:path-to-regexp@1.2.1/index.js",
      "npm:isarray@0.0.1.js",
      "npm:isarray@0.0.1/index.js",
      "npm:marked@0.3.5.js",
      "npm:marked@0.3.5/lib/marked.js",
      "npm:lodash@4.11.1.js",
      "npm:lodash@4.11.1/lodash.js",
      "github:jspm/nodelibs-buffer@0.1.0.js",
      "github:jspm/nodelibs-buffer@0.1.0/index.js",
      "npm:buffer@3.6.0.js",
      "npm:buffer@3.6.0/index.js",
      "npm:isarray@1.0.0.js",
      "npm:isarray@1.0.0/index.js",
      "npm:ieee754@1.1.6.js",
      "npm:ieee754@1.1.6/index.js",
      "npm:base64-js@0.0.8.js",
      "npm:base64-js@0.0.8/lib/b64.js",
      "npm:jquery@2.2.3.js",
      "npm:jquery@2.2.3/dist/jquery.js",
      "npm:classnames@2.2.3.js",
      "npm:classnames@2.2.3/index.js",
      "github:twbs/bootstrap@3.3.6.js",
      "github:twbs/bootstrap@3.3.6/js/bootstrap.js",
      "github:components/jquery@2.2.1.js",
      "github:components/jquery@2.2.1/jquery.js",
      "github:cujojs/rest@1.3.2.js",
      "github:cujojs/rest@1.3.2/browser.js",
      "github:cujojs/rest@1.3.2/client/xhr.js",
      "github:cujojs/rest@1.3.2/client.js",
      "github:cujojs/rest@1.3.2/util/responsePromise.js",
      "github:cujojs/rest@1.3.2/util/normalizeHeaderName.js",
      "npm:when@3.7.7.js",
      "npm:when@3.7.7/when.js",
      "npm:when@3.7.7/lib/apply.js",
      "npm:when@3.7.7/lib/Promise.js",
      "npm:when@3.7.7/lib/env.js",
      "npm:when@3.7.7/lib/Scheduler.js",
      "npm:when@3.7.7/lib/makePromise.js",
      "npm:when@3.7.7/lib/TimeoutError.js",
      "npm:when@3.7.7/lib/decorators/unhandledRejection.js",
      "npm:when@3.7.7/lib/format.js",
      "npm:when@3.7.7/lib/decorators/with.js",
      "npm:when@3.7.7/lib/decorators/progress.js",
      "npm:when@3.7.7/lib/decorators/iterate.js",
      "npm:when@3.7.7/lib/decorators/inspect.js",
      "npm:when@3.7.7/lib/state.js",
      "npm:when@3.7.7/lib/decorators/fold.js",
      "npm:when@3.7.7/lib/decorators/flow.js",
      "npm:when@3.7.7/lib/decorators/array.js",
      "npm:when@3.7.7/lib/decorators/timed.js",
      "github:cujojs/rest@1.3.2/UrlBuilder.js",
      "github:cujojs/rest@1.3.2/util/mixin.js",
      "github:cujojs/rest@1.3.2/client/default.js"
    ],
    "vendor.js": [
      "npm:react-dom@15.0.1.js",
      "npm:react-dom@15.0.1/dist/react-dom.js",
      "npm:react@15.0.1.js",
      "npm:react@15.0.1/dist/react.js",
      "github:jspm/nodelibs-process@0.1.2.js",
      "github:jspm/nodelibs-process@0.1.2/index.js",
      "npm:process@0.11.2.js",
      "npm:process@0.11.2/browser.js",
      "npm:react-date-picker@4.0.10.js",
      "npm:react-date-picker@4.0.10/lib/index.js",
      "npm:react-date-picker@4.0.10/lib/onEnter.js",
      "npm:react-date-picker@4.0.10/lib/toMoment.js",
      "npm:react-date-picker@4.0.10/lib/config.js",
      "npm:react-date-picker@4.0.10/lib/utils/getWeekDayNames.js",
      "npm:moment@2.12.0.js",
      "npm:moment@2.12.0/moment.js",
      "npm:react-date-picker@4.0.10/lib/Header.js",
      "npm:react-date-picker@4.0.10/lib/DecadeView.js",
      "npm:react-date-picker@4.0.10/lib/utils/isInRange.js",
      "npm:react-date-picker@4.0.10/lib/utils/asConfig.js",
      "npm:object-assign@4.0.1.js",
      "npm:object-assign@4.0.1/index.js",
      "npm:react-date-picker@4.0.10/lib/utils/format.js",
      "npm:react-date-picker@4.0.10/lib/YearView.js",
      "npm:react-date-picker@4.0.10/lib/MonthView.js",
      "npm:page@1.7.1.js",
      "npm:page@1.7.1/index.js",
      "npm:path-to-regexp@1.2.1.js",
      "npm:path-to-regexp@1.2.1/index.js",
      "npm:isarray@0.0.1.js",
      "npm:isarray@0.0.1/index.js",
      "npm:marked@0.3.5.js",
      "npm:marked@0.3.5/lib/marked.js",
      "npm:lodash@4.11.1.js",
      "npm:lodash@4.11.1/lodash.js",
      "github:jspm/nodelibs-buffer@0.1.0.js",
      "github:jspm/nodelibs-buffer@0.1.0/index.js",
      "npm:buffer@3.6.0.js",
      "npm:buffer@3.6.0/index.js",
      "npm:isarray@1.0.0.js",
      "npm:isarray@1.0.0/index.js",
      "npm:ieee754@1.1.6.js",
      "npm:ieee754@1.1.6/index.js",
      "npm:base64-js@0.0.8.js",
      "npm:base64-js@0.0.8/lib/b64.js",
      "npm:jquery@2.2.3.js",
      "npm:jquery@2.2.3/dist/jquery.js",
      "npm:fluxxor@1.7.3.js",
      "npm:fluxxor@1.7.3/index.js",
      "npm:fluxxor@1.7.3/version.js",
      "npm:fluxxor@1.7.3/lib/create_store.js",
      "npm:fluxxor@1.7.3/lib/util/inherits.js",
      "npm:fluxxor@1.7.3/lib/store.js",
      "npm:lodash@3.10.1/lang/isObject.js",
      "npm:lodash@3.10.1/lang/isFunction.js",
      "npm:eventemitter3@0.1.6.js",
      "npm:eventemitter3@0.1.6/index.js",
      "npm:lodash@3.10.1/collection/forEach.js",
      "npm:lodash@3.10.1/internal/createForEach.js",
      "npm:lodash@3.10.1/lang/isArray.js",
      "npm:lodash@3.10.1/internal/isObjectLike.js",
      "npm:lodash@3.10.1/internal/isLength.js",
      "npm:lodash@3.10.1/internal/getNative.js",
      "npm:lodash@3.10.1/lang/isNative.js",
      "npm:lodash@3.10.1/internal/bindCallback.js",
      "npm:lodash@3.10.1/utility/identity.js",
      "npm:lodash@3.10.1/internal/baseEach.js",
      "npm:lodash@3.10.1/internal/createBaseEach.js",
      "npm:lodash@3.10.1/internal/toObject.js",
      "npm:lodash@3.10.1/internal/getLength.js",
      "npm:lodash@3.10.1/internal/baseProperty.js",
      "npm:lodash@3.10.1/internal/baseForOwn.js",
      "npm:lodash@3.10.1/object/keys.js",
      "npm:lodash@3.10.1/internal/shimKeys.js",
      "npm:lodash@3.10.1/object/keysIn.js",
      "npm:lodash@3.10.1/internal/isIndex.js",
      "npm:lodash@3.10.1/lang/isArguments.js",
      "npm:lodash@3.10.1/internal/isArrayLike.js",
      "npm:lodash@3.10.1/internal/baseFor.js",
      "npm:lodash@3.10.1/internal/createBaseFor.js",
      "npm:lodash@3.10.1/internal/arrayEach.js",
      "npm:fluxxor@1.7.3/lib/store_watch_mixin.js",
      "npm:fluxxor@1.7.3/lib/flux_child_mixin.js",
      "npm:fluxxor@1.7.3/lib/flux_mixin.js",
      "npm:fluxxor@1.7.3/lib/flux.js",
      "npm:fluxxor@1.7.3/lib/dispatcher.js",
      "npm:lodash@3.10.1/array/uniq.js",
      "npm:lodash@3.10.1/internal/sortedUniq.js",
      "npm:lodash@3.10.1/internal/isIterateeCall.js",
      "npm:lodash@3.10.1/internal/baseUniq.js",
      "npm:lodash@3.10.1/internal/createCache.js",
      "npm:lodash@3.10.1/internal/SetCache.js",
      "npm:lodash@3.10.1/internal/cachePush.js",
      "npm:lodash@3.10.1/internal/cacheIndexOf.js",
      "npm:lodash@3.10.1/internal/baseIndexOf.js",
      "npm:lodash@3.10.1/internal/indexOfNaN.js",
      "npm:lodash@3.10.1/internal/baseCallback.js",
      "npm:lodash@3.10.1/utility/property.js",
      "npm:lodash@3.10.1/internal/isKey.js",
      "npm:lodash@3.10.1/internal/basePropertyDeep.js",
      "npm:lodash@3.10.1/internal/toPath.js",
      "npm:lodash@3.10.1/internal/baseToString.js",
      "npm:lodash@3.10.1/internal/baseGet.js",
      "npm:lodash@3.10.1/internal/baseMatchesProperty.js",
      "npm:lodash@3.10.1/array/last.js",
      "npm:lodash@3.10.1/internal/isStrictComparable.js",
      "npm:lodash@3.10.1/internal/baseSlice.js",
      "npm:lodash@3.10.1/internal/baseIsEqual.js",
      "npm:lodash@3.10.1/internal/baseIsEqualDeep.js",
      "npm:lodash@3.10.1/lang/isTypedArray.js",
      "npm:lodash@3.10.1/internal/equalObjects.js",
      "npm:lodash@3.10.1/internal/equalByTag.js",
      "npm:lodash@3.10.1/internal/equalArrays.js",
      "npm:lodash@3.10.1/internal/arraySome.js",
      "npm:lodash@3.10.1/internal/baseMatches.js",
      "npm:lodash@3.10.1/internal/getMatchData.js",
      "npm:lodash@3.10.1/object/pairs.js",
      "npm:lodash@3.10.1/internal/baseIsMatch.js",
      "npm:lodash@3.10.1/object/findKey.js",
      "npm:lodash@3.10.1/internal/createFindKey.js",
      "npm:lodash@3.10.1/internal/baseFind.js",
      "npm:lodash@3.10.1/collection/size.js",
      "npm:lodash@3.10.1/collection/map.js",
      "npm:lodash@3.10.1/internal/baseMap.js",
      "npm:lodash@3.10.1/internal/arrayMap.js",
      "npm:lodash@3.10.1/array/intersection.js",
      "npm:lodash@3.10.1/function/restParam.js",
      "npm:lodash@3.10.1/object/forOwn.js",
      "npm:lodash@3.10.1/internal/createForOwn.js",
      "npm:lodash@3.10.1/object/mapValues.js",
      "npm:lodash@3.10.1/internal/createObjectMapper.js",
      "npm:lodash@3.10.1/lang/clone.js",
      "npm:lodash@3.10.1/internal/baseClone.js",
      "npm:lodash@3.10.1/internal/initCloneObject.js",
      "npm:lodash@3.10.1/internal/initCloneByTag.js",
      "npm:lodash@3.10.1/internal/bufferClone.js",
      "npm:lodash@3.10.1/internal/initCloneArray.js",
      "npm:lodash@3.10.1/internal/baseAssign.js",
      "npm:lodash@3.10.1/internal/baseCopy.js",
      "npm:lodash@3.10.1/internal/arrayCopy.js",
      "npm:lodash@3.10.1/lang/isString.js",
      "npm:lodash@3.10.1/collection/reduce.js",
      "npm:lodash@3.10.1/internal/createReduce.js",
      "npm:lodash@3.10.1/internal/baseReduce.js",
      "npm:lodash@3.10.1/internal/arrayReduce.js",
      "npm:object-path@0.6.0.js",
      "npm:object-path@0.6.0/index.js",
      "npm:classnames@2.2.3.js",
      "npm:classnames@2.2.3/index.js",
      "github:twbs/bootstrap@3.3.6.js",
      "github:twbs/bootstrap@3.3.6/js/bootstrap.js",
      "github:components/jquery@2.2.1.js",
      "github:components/jquery@2.2.1/jquery.js",
      "github:cujojs/rest@1.3.2/interceptor/mime.js",
      "npm:when@3.7.7.js",
      "npm:when@3.7.7/when.js",
      "npm:when@3.7.7/lib/apply.js",
      "npm:when@3.7.7/lib/Promise.js",
      "npm:when@3.7.7/lib/env.js",
      "npm:when@3.7.7/lib/Scheduler.js",
      "npm:when@3.7.7/lib/makePromise.js",
      "npm:when@3.7.7/lib/TimeoutError.js",
      "npm:when@3.7.7/lib/decorators/unhandledRejection.js",
      "npm:when@3.7.7/lib/format.js",
      "npm:when@3.7.7/lib/decorators/with.js",
      "npm:when@3.7.7/lib/decorators/progress.js",
      "npm:when@3.7.7/lib/decorators/iterate.js",
      "npm:when@3.7.7/lib/decorators/inspect.js",
      "npm:when@3.7.7/lib/state.js",
      "npm:when@3.7.7/lib/decorators/fold.js",
      "npm:when@3.7.7/lib/decorators/flow.js",
      "npm:when@3.7.7/lib/decorators/array.js",
      "npm:when@3.7.7/lib/decorators/timed.js",
      "github:cujojs/rest@1.3.2/mime/registry.js",
      "github:cujojs/rest@1.3.2/mime/type/text/plain.js",
      "github:cujojs/rest@1.3.2/mime/type/multipart/form-data.js",
      "github:cujojs/rest@1.3.2/mime/type/application/x-www-form-urlencoded.js",
      "github:cujojs/rest@1.3.2/mime/type/application/json.js",
      "github:cujojs/rest@1.3.2/mime/type/application/hal.js",
      "github:cujojs/rest@1.3.2/util/responsePromise.js",
      "github:cujojs/rest@1.3.2/util/normalizeHeaderName.js",
      "github:cujojs/rest@1.3.2/util/lazyPromise.js",
      "github:cujojs/rest@1.3.2/util/find.js",
      "github:cujojs/rest@1.3.2/interceptor/template.js",
      "github:cujojs/rest@1.3.2/util/mixin.js",
      "github:cujojs/rest@1.3.2/util/uriTemplate.js",
      "github:cujojs/rest@1.3.2/util/uriEncoder.js",
      "github:cujojs/rest@1.3.2/interceptor.js",
      "github:cujojs/rest@1.3.2/client.js",
      "github:cujojs/rest@1.3.2/client/default.js",
      "github:cujojs/rest@1.3.2/interceptor/pathPrefix.js",
      "github:cujojs/rest@1.3.2/UrlBuilder.js",
      "github:cujojs/rest@1.3.2/mime.js",
      "github:cujojs/rest@1.3.2/interceptor/errorCode.js",
      "github:cujojs/rest@1.3.2/interceptor/csrf.js",
      "github:cujojs/rest@1.3.2.js",
      "github:cujojs/rest@1.3.2/browser.js",
      "github:cujojs/rest@1.3.2/client/xhr.js"
    ]
  },

  map: {
    "bootstrap": "github:twbs/bootstrap@3.3.6",
    "classnames": "npm:classnames@2.2.3",
    "fluxxor": "npm:fluxxor@1.7.3",
    "jquery": "npm:jquery@2.2.3",
    "lodash": "npm:lodash@4.11.1",
    "marked": "npm:marked@0.3.5",
    "moment": "npm:moment@2.12.0",
    "page": "npm:page@1.7.1",
    "react": "npm:react@15.0.1",
    "react-date-picker": "npm:react-date-picker@4.0.10",
    "react-dom": "npm:react-dom@15.0.1",
    "rest": "github:cujojs/rest@1.3.2",
    "github:cujojs/rest@1.3.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0",
      "when": "npm:when@3.7.7"
    },
    "github:jspm/nodelibs-assert@0.1.0": {
      "assert": "npm:assert@1.3.0"
    },
    "github:jspm/nodelibs-buffer@0.1.0": {
      "buffer": "npm:buffer@3.6.0"
    },
    "github:jspm/nodelibs-domain@0.1.0": {
      "domain-browser": "npm:domain-browser@1.1.7"
    },
    "github:jspm/nodelibs-events@0.1.1": {
      "events": "npm:events@1.0.2"
    },
    "github:jspm/nodelibs-http@1.7.1": {
      "Base64": "npm:Base64@0.2.1",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "url": "github:jspm/nodelibs-url@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "github:jspm/nodelibs-https@0.1.0": {
      "https-browserify": "npm:https-browserify@0.0.0"
    },
    "github:jspm/nodelibs-os@0.1.0": {
      "os-browserify": "npm:os-browserify@0.1.2"
    },
    "github:jspm/nodelibs-path@0.1.0": {
      "path-browserify": "npm:path-browserify@0.0.0"
    },
    "github:jspm/nodelibs-process@0.1.2": {
      "process": "npm:process@0.11.2"
    },
    "github:jspm/nodelibs-stream@0.1.0": {
      "stream-browserify": "npm:stream-browserify@1.0.0"
    },
    "github:jspm/nodelibs-string_decoder@0.1.0": {
      "string_decoder": "npm:string_decoder@0.10.31"
    },
    "github:jspm/nodelibs-url@0.1.0": {
      "url": "npm:url@0.10.3"
    },
    "github:jspm/nodelibs-util@0.1.0": {
      "util": "npm:util@0.10.3"
    },
    "github:jspm/nodelibs-zlib@0.1.0": {
      "browserify-zlib": "npm:browserify-zlib@0.1.4"
    },
    "github:twbs/bootstrap@3.3.6": {
      "jquery": "github:components/jquery@2.2.1"
    },
    "npm:acorn@1.2.2": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "stream": "github:jspm/nodelibs-stream@0.1.0"
    },
    "npm:asap@2.0.3": {
      "domain": "github:jspm/nodelibs-domain@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:assert@1.3.0": {
      "util": "npm:util@0.10.3"
    },
    "npm:babel-plugin-syntax-flow@6.5.0": {
      "babel-runtime": "npm:babel-runtime@5.8.38"
    },
    "npm:babel-runtime@5.8.38": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:browserify-zlib@0.1.4": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "pako": "npm:pako@0.2.8",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "readable-stream": "npm:readable-stream@2.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:buffer@3.6.0": {
      "base64-js": "npm:base64-js@0.0.8",
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "ieee754": "npm:ieee754@1.1.6",
      "isarray": "npm:isarray@1.0.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:core-js@1.2.6": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:core-util-is@1.0.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:domain-browser@1.1.7": {
      "events": "github:jspm/nodelibs-events@0.1.1"
    },
    "npm:encoding@0.1.12": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "iconv-lite": "npm:iconv-lite@0.4.13"
    },
    "npm:eventemitter3@0.1.6": {
      "process": "github:jspm/nodelibs-process@0.1.2",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:falafel@1.2.0": {
      "acorn": "npm:acorn@1.2.2",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "foreach": "npm:foreach@2.0.5",
      "isarray": "npm:isarray@0.0.1",
      "object-keys": "npm:object-keys@1.0.9"
    },
    "npm:fbjs@0.8.0": {
      "babel-plugin-syntax-flow": "npm:babel-plugin-syntax-flow@6.5.0",
      "core-js": "npm:core-js@1.2.6",
      "isomorphic-fetch": "npm:isomorphic-fetch@2.2.1",
      "loose-envify": "npm:loose-envify@1.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "promise": "npm:promise@7.1.1",
      "ua-parser-js": "npm:ua-parser-js@0.7.10"
    },
    "npm:fluxxor@1.7.3": {
      "eventemitter3": "npm:eventemitter3@0.1.6",
      "lodash": "npm:lodash@3.10.1",
      "object-path": "npm:object-path@0.6.0"
    },
    "npm:https-browserify@0.0.0": {
      "http": "github:jspm/nodelibs-http@1.7.1"
    },
    "npm:iconv-lite@0.4.13": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "string_decoder": "github:jspm/nodelibs-string_decoder@0.1.0",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:inherits@2.0.1": {
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:inline-process-browser@2.0.1": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "falafel": "npm:falafel@1.2.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "through2": "npm:through2@0.6.5"
    },
    "npm:isomorphic-fetch@2.2.1": {
      "node-fetch": "npm:node-fetch@1.5.1",
      "whatwg-fetch": "npm:whatwg-fetch@0.11.0"
    },
    "npm:lodash@3.10.1": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:lodash@4.11.1": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:loose-envify@1.1.0": {
      "js-tokens": "npm:js-tokens@1.0.3",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:node-fetch@1.5.1": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "encoding": "npm:encoding@0.1.12",
      "http": "github:jspm/nodelibs-http@1.7.1",
      "https": "github:jspm/nodelibs-https@0.1.0",
      "is-stream": "npm:is-stream@1.1.0",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "url": "github:jspm/nodelibs-url@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0",
      "zlib": "github:jspm/nodelibs-zlib@0.1.0"
    },
    "npm:os-browserify@0.1.2": {
      "os": "github:jspm/nodelibs-os@0.1.0"
    },
    "npm:page@1.7.1": {
      "path-to-regexp": "npm:path-to-regexp@1.2.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:pako@0.2.8": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:path-browserify@0.0.0": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:path-to-regexp@1.2.1": {
      "isarray": "npm:isarray@0.0.1"
    },
    "npm:process-nextick-args@1.0.6": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:process@0.11.2": {
      "assert": "github:jspm/nodelibs-assert@0.1.0"
    },
    "npm:promise@7.1.1": {
      "asap": "npm:asap@2.0.3",
      "fs": "github:jspm/nodelibs-fs@0.1.2"
    },
    "npm:punycode@1.3.2": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:react-date-picker@4.0.10": {
      "moment": "npm:moment@2.12.0",
      "object-assign": "npm:object-assign@4.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "react": "npm:react@15.0.1"
    },
    "npm:react-dom@15.0.1": {
      "react": "npm:react@15.0.1"
    },
    "npm:react@15.0.1": {
      "fbjs": "npm:fbjs@0.8.0",
      "loose-envify": "npm:loose-envify@1.1.0",
      "object-assign": "npm:object-assign@4.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:readable-stream@1.0.34": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "core-util-is": "npm:core-util-is@1.0.2",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "isarray": "npm:isarray@0.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "stream-browserify": "npm:stream-browserify@1.0.0",
      "string_decoder": "npm:string_decoder@0.10.31"
    },
    "npm:readable-stream@2.1.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "core-util-is": "npm:core-util-is@1.0.2",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "inline-process-browser": "npm:inline-process-browser@2.0.1",
      "isarray": "npm:isarray@1.0.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "process-nextick-args": "npm:process-nextick-args@1.0.6",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "string_decoder": "npm:string_decoder@0.10.31",
      "unreachable-branch-transform": "npm:unreachable-branch-transform@0.5.1",
      "util-deprecate": "npm:util-deprecate@1.0.2"
    },
    "npm:recast@0.11.5": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "ast-types": "npm:ast-types@0.8.16",
      "esprima": "npm:esprima@2.7.2",
      "os": "github:jspm/nodelibs-os@0.1.0",
      "private": "npm:private@0.1.6",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "source-map": "npm:source-map@0.5.3"
    },
    "npm:source-map@0.5.3": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:stream-browserify@1.0.0": {
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "readable-stream": "npm:readable-stream@1.0.34"
    },
    "npm:string_decoder@0.10.31": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:through2@0.6.5": {
      "process": "github:jspm/nodelibs-process@0.1.2",
      "readable-stream": "npm:readable-stream@1.0.34",
      "util": "github:jspm/nodelibs-util@0.1.0",
      "xtend": "npm:xtend@4.0.1"
    },
    "npm:ua-parser-js@0.7.10": {
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:unreachable-branch-transform@0.5.1": {
      "esmangle-evaluator": "npm:esmangle-evaluator@1.0.0",
      "recast": "npm:recast@0.11.5",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:url@0.10.3": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "punycode": "npm:punycode@1.3.2",
      "querystring": "npm:querystring@0.2.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:util-deprecate@1.0.2": {
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:util@0.10.3": {
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:when@3.7.7": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    }
  }
});
